channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - conda-build=3.21.7
  - pip=21.3
  - pip:
    - -r "./requirements-dev.txt"
    - astor==0.8.1
    - cached-property==1.5.1
    - holidays==0.12
    - jsons==1.6.1
    - more_itertools==8.12.0
    # Pin nltk to 3.6.5. gem-metrics does not work with higher version of NLTK.
    - nltk==3.6.5
    - pandas==1.3.5
    - parsimonious==0.8.1
    - pint==0.18
